### ISSUE TITLE
Resources will not be re-indexed when editing Resource Metadata ACLs in the Collection Definition Editor in the Administration Console

### ISSUE THREAD

**Issue by smclaughlin520** [equella/Equella#229] opened 2017-06-28 22:20 UTC
"Discovered a while ago, but no-one logged anything about it. 

 From memory it uses some SQL to detect which items should be affected, but it always returns nothing (dodgy query)
 
 Changing the other ACLs causes re-indexes as expected.

Issue Converted from original Equella JIRA

**Comment by abidingotter** [comment] 2017-08-08 01:51
This what the final query to find the items to re-index looks like: (parameter values will vary...)

WITH query AS (
	select ROW_NUMBER() OVER (order by item0_.id asc) as __hibernate_row_nr__
	, item0_.id as col_0_0_ 
	from item item0_ 
	where (
		'e139d81d-8904-48f6-b04b-9ea10418b6e7' in (item0_.metadata_security_targets)) 
		and item0_.institution_id=3 
		and item0_.date_for_index<GETDATE() and item0_.id>=-1
	) 
SELECT * FROM query WHERE __hibernate_row_nr__ BETWEEN 1 AND 500

however, item0_.metadata_security_targets is just a single column, with a value of "string" in most cases, and "string,e139d81d-8904-48f6-b04b-9ea10418b6e7" in the case that was supposed to have been picked up, however SQL "IN" doesn't work as a substring operation, it's a set operation.

This is why nothing gets picked up.  The HQL (in ItemMetadataFilter.java) that generates this SQL could probably be changed to "LIKE" instead of "IN" and it might work.

**Comment by abidingotter** [comment] 2017-08-08 02:01
LIKE doesn't work:

Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Collection
	at com.tle.core.hibernate.type.HibernateCsvType.nullSafeSet(HibernateCsvType.java:124)
	at org.hibernate.type.CustomType.nullSafeSet(CustomType.java:146)
	at org.hibernate.param.NamedParameterSpecification.bind(NamedParameterSpecification.java:67)
	at org.hibernate.loader.hql.QueryLoader.bindParameterValues(QueryLoader.java:578)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1716)
	at org.hibernate.loader.Loader.scroll(Loader.java:2614)
	at org.hibernate.loader.hql.QueryLoader.scroll(QueryLoader.java:521)
	at org.hibernate.hql.ast.QueryTranslatorImpl.scroll(QueryTranslatorImpl.java:417)
	at org.hibernate.engine.query.HQLQueryPlan.performScroll(HQLQueryPlan.java:269)
	at org.hibernate.impl.SessionImpl.scroll(SessionImpl.java:1353)
	at org.hibernate.impl.QueryImpl.scroll(QueryImpl.java:90)
	at org.hibernate.impl.QueryImpl.scroll(QueryImpl.java:80)
	at com.tle.core.dao.helpers.DMLPartitioner.withSession(DMLPartitioner.java:52)
	at com.tle.core.dao.helpers.DMLPartitioner.doInHibernate(DMLPartitioner.java:31)
	at org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:419)
	at com.tle.core.hibernate.dao.AbstractHibernateDao$1.doExecute(AbstractHibernateDao.java:40)
	at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:339)
	at com.tle.core.dao.impl.ItemDaoImpl.updateIndexTimes(ItemDaoImpl.java:542)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)
	at com.tle.core.services.item.impl.ItemServiceImpl.updateIndexTimes(ItemServiceImpl.java:412)
	at com.tle.freetext.reindexing.ReindexFilter.updateIndexTimes(ReindexFilter.java:17)
	at com.tle.core.services.item.FreeTextServiceImpl.itemReindexEvent(FreeTextServiceImpl.java:264)
	at com.tle.core.events.ItemReindexEvent.postEvent(ItemReindexEvent.java:34)
	at com.tle.core.events.ItemReindexEvent.postEvent(ItemReindexEvent.java:1)
	at com.tle.core.services.impl.EventServiceImpl.executeEventNow(EventServiceImpl.java:122)
	... 11 more

**Comment by cbeach47** [comment] 2018-01-08 16:42
Taking a look at this now

**Comment by cbeach47** [comment] 2018-01-19 15:32
Fix merged into Master.  During the primary test cycle, it'd be good for a run through with Oracle DB and SQL Server even though the syntax should be valid for all 3 supported DBs.

**Closed by cbeach47** 2018-01-19 15:32 UTC
Labels: Unicon SE, bug
