### ISSUE TITLE
Review Technical Set Up documentation as a team

### ISSUE THREAD

**Issue by smclaughlin520** [equella/Equella#19] opened 2017-03-31 17:03 UTC
- [ ] Placeholder for Team to review tech documentation

**Comment by ddelblanco** [comment] 2017-04-04 18:48
I've arrived to the point when we should download the jars. 
I've tried the user that Pearson sent in 3 different ways:

nexus.username=myusername
nexus.username=PEROOT/myusername
nexus.username=PEROOT\myusername

And none of them downloads the jars. 

Can we imagine an alternative way to do this to set up the first environment? After that we can create our repo or any other long term solution, but at this moment, we need a way to solve this problem to continue.

**Comment by doolse** [comment] 2017-04-05 07:26
As mentioned in #2 I've made the necessary changes to not rely on Pearson nexus but instead a locally installed repo which you can download here - https://bitbucket.org/equellateam/equella-master/downloads/equella-deps.zip

The .zip contains an "equella-deps" folder which must be place in your home directory for the ant scripts to find it.

The necessary changes are spread across a single commit to the 3 main repos in a "doolse/nonexus" branch - 
* https://bitbucket.org/equellateam/equella-master/branch/doolse%2Fnonexus
* https://bitbucket.org/equellateam/platform/branch/doolse%2Fnonexus
* https://bitbucket.org/equellateam/equella-rest-interfaces/branch/doolse%2Fnonexus

The branches were all based off what was in the "release/6.4-edalex" branch, so you're probably best off cherry-picking the top commit from each "doolse/nonexus" branch instead of merging.

**Comment by ddelblanco** [comment] 2017-04-05 15:18
Thanks!  Sounds perfect!!!

**Comment by drewwills** [comment] 2017-04-05 17:16
@ddelblanco and @doolse -- The information in this ticket is valuable (very much), but it's not related to the task @smclaughlin520 had in mind when she created it.

We need to do one of two things:

  - (1) Document what this `equella-deps` thing is (and how to set it up) in a wiki page within this repo;  or
  - (2) Take the contents of this zip and `git add` them within the project and also change the Ant behavior to find them in the new location

I believe either option is temporary.  Once the sources are public, I believe we will tackle these libraries one-by-one to reach a more permanent solution.  (Unicon etam members can help with this effort.)

My vote is for option (1), but I'm flexible.

**Comment by n4074** [comment] 2017-05-16 00:47
The `equella-master` (https://bitbucket.org/equellateam/equella-master/downloads/equella-deps.zip) repository appears to be private. Where can I get `equella-deps`?

**Comment by ddelblanco** [comment] 2017-05-16 18:32
Hello:

We are just in the process of removing all the need of that zip file.  This is part of a bigger effort to make all this code full open source so everyone can download and use it. This will need a few days or weeks more, but on that moment, you will be able to download the code, build equella and run it without needing any  external zip file. 

Sorry, but I need to ask you to have a little patience meanwhile we finish that work! Some of the process of this "open sourcing effort" is to remove from that zip some libraries that are not the right ones for an open source project due to license incompatibilities. That's why the zip is not in an open repo.

**Comment by n4074** [comment] 2017-05-17 02:07
No problem. Just wasn't sure if this was simply an oversight. So just to confirm, at this stage until that work has been performed and equella-deps.zip is no longer required, there's no way for us to build the project?

Thanks.

**Comment by drewwills** [comment] 2017-05-17 17:01
@n4074 -- I bet we could probably email you a copy of dependencies.zip (for as long as it's still needed).

**Comment by n4074** [comment] 2017-05-18 04:31
Hi,

That would be helpful if you are happy to do so. The best address would be entrench.postdate.why+github@gmail.com.

Thanks

**Comment by drewwills** [comment] 2017-05-18 17:34
Sent, but the file is large.  (Please let me know if you can't receive it.)

**Comment by n4074** [comment] 2017-05-18 23:52
Hi Drew,

Thanks so much. I have successfully retrieved the file.

**Comment by drewwills** [comment] 2017-05-26 00:30
@smclaughlin520 -- This is the only open item remaining in this milestone.

Could we poll the devs and see if they feel the setup docs are sufficiently mature (for the present), or if we need some sort of coordinated review step.  If we need one, let's get it scheduled.

**Comment by cbeach47** [comment] 2017-05-26 16:12
I confirmed with @doolse last evening that he is good with all documentation moving over the the equella.github.io repo.  I am revising the tech documentation (esp regarding the new sbt process) now.

**Comment by cbeach47** [comment] 2017-06-02 17:37
Main docs complete.  Closing this issue.
https://equella.github.io/gettingstarted/InstallingEquella.html
https://equella.github.io/gettingstarted/SettingUpAnEquellaDevEnvironment.html

**Closed by cbeach47** 2017-06-02 17:37 UTC
