### ISSUE TITLE
Deleting workflow step can fail if an item is moderation still

### ISSUE THREAD

**Issue by doolse** [equella/Equella#375] opened 2017-10-23 06:20 UTC
Long story short, depending on the order of entries in the db, you might delete a referenced node while it's still in use.

**Comment by mrblippy** [comment] 2017-10-25 00:04
Different constraint violation this time

11:02:38,770 ERROR [JDBCExceptionReporter] ERROR: update or delete on table "workflow_node_status" violates foreign key constraint "fk94de4f876b3d7505" on table "workflow_message"
  Detail: Key (id)=(16080) is still referenced from table "workflow_message".
11:02:38,771 ERROR [RemoteInterceptor] could not execute update query; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute update query
org.springframework.dao.DataIntegrityViolationException: could not execute update query; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute update query
	at org.springframework.orm.hibernate3.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:624)
	at org.springframework.orm.hibernate3.HibernateAccessor.convertHibernateAccessException(HibernateAccessor.java:412)
	at org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:424)
	at com.tle.core.hibernate.dao.AbstractHibernateDao$1.doExecute(AbstractHibernateDao.java:58)
	at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:339)
	at com.tle.core.workflow.dao.impl.WorkflowDaoImpl.markForReset(WorkflowDaoImpl.java:67)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)
	at com.tle.core.workflow.standard.service.impl.WorkflowStandardServiceImpl.workflowNodesSaved(WorkflowStandardServiceImpl.java:76)
	at com.tle.core.workflow.service.impl.WorkflowServiceImpl.editNodes(WorkflowServiceImpl.java:444)
	at com.tle.core.workflow.service.impl.WorkflowServiceImpl.stopEdit(WorkflowServiceImpl.java:385)
	at com.tle.core.security.impl.MethodSecurityInteceptor.invoke(MethodSecurityInteceptor.java:40)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)
	at com.tle.core.workflow.service.impl.WorkflowServiceImpl.stopEdit(WorkflowServiceImpl.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:310)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:198)
	at com.sun.proxy.$Proxy164.stopEdit(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.remoting.support.RemoteInvocation.invoke(RemoteInvocation.java:205)
	at org.springframework.remoting.support.DefaultRemoteInvocationExecutor.invoke(DefaultRemoteInvocationExecutor.java:38)
	at org.springframework.remoting.support.RemoteInvocationBasedExporter.invoke(RemoteInvocationBasedExporter.java:78)
	at com.tle.web.remoting.impl.RemoteInterceptor.invoke(RemoteInterceptor.java:146)
	at org.springframework.remoting.support.RemoteInvocationBasedExporter.invokeAndCreateResult(RemoteInvocationBasedExporter.java:114)
	at org.springframework.remoting.httpinvoker.HttpInvokerServiceExporter.handleRequest(HttpInvokerServiceExporter.java:74)
	at com.tle.web.remoting.impl.RemoteInterceptor.handleRequest(RemoteInterceptor.java:99)
	at com.tle.web.remoting.impl.AbstractRemoteHandler.service(AbstractRemoteHandler.java:74)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at com.tle.web.dispatcher.ServletDispatcher.dispatch(ServletDispatcher.java:98)
	at com.tle.web.dispatcher.RequestDispatchFilter.doFilter(RequestDispatchFilter.java:102)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute update query
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:96)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66)
	at org.hibernate.hql.ast.exec.BasicExecutor.execute(BasicExecutor.java:110)
	at org.hibernate.hql.ast.QueryTranslatorImpl.executeUpdate(QueryTranslatorImpl.java:423)
	at org.hibernate.engine.query.HQLQueryPlan.performExecuteUpdate(HQLQueryPlan.java:283)
	at org.hibernate.impl.SessionImpl.executeUpdate(SessionImpl.java:1288)
	at org.hibernate.impl.QueryImpl.executeUpdate(QueryImpl.java:117)
	at com.tle.core.workflow.dao.impl.WorkflowDaoImpl$1.doInHibernate(WorkflowDaoImpl.java:87)
	at org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:419)
	... 50 more
Caused by: org.postgresql.util.PSQLException: ERROR: update or delete on table "workflow_node_status" violates foreign key constraint "fk94de4f876b3d7505" on table "workflow_message"
  Detail: Key (id)=(16080) is still referenced from table "workflow_message".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2161)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1890)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:559)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:417)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:363)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.hibernate.hql.ast.exec.BasicExecutor.execute(BasicExecutor.java:101)
	... 56 more

**Comment by mrblippy** [comment] 2017-10-25 00:31
It's now fixed

**Closed by mrblippy** 2017-10-25 00:31 UTC
Labels: bug, Ready for 6.5 GA Testing
