### ISSUE TITLE
Custom links can't open in new tab - New UI - 6.6r5

### ISSUE THREAD

**Issue by alejopachons** [equella/Equella#624] opened 2018-11-26 19:38 UTC
Currently, custom links can't be opened in new tab.

**Comment by edalex-ian** [comment] 2018-12-11 22:59
Heya @doolse ,

I'm slightly confused with the flurry of activity, but is this one now ready for test? (Looks like it from above, but then I recall you may have said something.... :confused: )

Cheers.

**Comment by doolse** [comment] 2018-12-11 23:18
Yep this one is ready. I believe the one you're thinking of is #640 which was mistakenly referenced in a commit and isn't fixed.

**Comment by SammyIsConfused** [comment] 2018-12-12 04:01
Confirmed fixed in 6.6.r18.

**Comment by doolse** [comment] 2018-12-12 04:16
@SammyIsConfused Although reported in 6.6, it's only been fixed in master, if it was merged back into 6.6 it would have the "Backport 6.6" label on it. So i'm not sure what you tested but here is the testing details:

* Create/edit a custom link and set the "Open in new window" flag
* Save it - (new ui will need reloading to see menu link changes)
* Click on the link and see if it opens in a new window

**Comment by SammyIsConfused** [comment] 2018-12-12 04:34
@doolse my bad, mixed up my 6.6 tab with my 6.7 tab. No wonder it worked. Sorry about that!

**Comment by edalex-ian** [comment] 2018-12-12 05:18
Alright, looks good then for 2018.2.

**Closed by edalex-ian** 2018-12-12 05:18 UTC
Labels: bug
